import { AppSettings, Grade, LibraryItem, UserData } from "./types";

export const DEFAULT_ISLAND_LEVELS = [
  { level: 1, minExp: 0, title: "荒蕪小島", icon: "🏝️" },
  { level: 2, minExp: 100, title: "萌芽之島", icon: "🌱" },
  { level: 3, minExp: 300, title: "森林之島", icon: "🌲" },
  { level: 4, minExp: 600, title: "村落之島", icon: "⛺" },
  { level: 5, minExp: 1000, title: "繁榮城鎮", icon: "🏰" },
  { level: 6, minExp: 1500, title: "天空之城", icon: "☁️" },
  { level: 7, minExp: 2500, title: "星際基地", icon: "🚀" },
];

export const DEFAULT_REWARDS = [
  { id: 'r1', name: '看一集動漫', cost: 100, icon: '📺' },
  { id: 'r2', name: '喝一杯手搖飲', cost: 50, icon: '🧋' },
  { id: 'r3', name: '休息 30 分鐘', cost: 30, icon: '🛌' },
  { id: 'r4', name: '玩 1 小時遊戲', cost: 200, icon: '🎮' },
];

export const DEFAULT_SETTINGS: AppSettings = {
  passingScore: 80,
  expMemo: 10,
  expPractice: 5,
  expCorrect: 5,
  expScoreEntry: 10,
  expPass: 20,
  expPomodoro: 5,
  coinMemo: 10,       // Default same as EXP
  coinPractice: 5,
  coinCorrect: 5,
  coinScoreEntry: 10,
  coinPass: 20,
  coinPomodoro: 5,
  islandLevels: DEFAULT_ISLAND_LEVELS,
  rewards: DEFAULT_REWARDS,
  appTitle: "Island Study Log",
  appSubtitle: "V7.0 Release",
  gasUrl: "",
  geminiApiKey: "", // Default empty for security
  autoCloudSave: false
};

export const DEFAULT_USER_DATA: UserData = { exp: 0, coins: 0, logs: {} };

export const DEFAULT_LIBRARY: LibraryItem[] = [
  { id: 1, title: 'Google 翻譯', url: 'https://translate.google.com', category: '🛠️ 實用工具' },
  { id: 2, title: 'NotebookLM', url: 'https://notebooklm.google.com', category: '🤖 AI 助手' },
  { id: 3, title: 'Lofi Girl Music', url: 'https://lofigirl.com', category: '🎵 專注音樂' },
];

export const DEFAULT_CATEGORIES = ["📚 參考資料", "📺 影音教學", "🛠️ 實用工具", "🎵 專注音樂", "🤖 AI 助手"];

export const DEFAULT_GRADES: Grade[] = [
  {
    "id": "g_1767461177303",
    "name": "七年級",
    "subjects": [
      {
        "id": "sub_1767461177303_bgycf73m6",
        "name": "國文",
        "rows": [
          {
            "id": 1767507140709.1868,
            "topic": "L7",
            "note": false,
            "memo": "https://notebooklm.google.com/notebook/60ac537e-bf3d-457b-93ce-b4ada4ac1a9b?artifactId=de3fb31d-bb92-4b9d-b54f-be6b6bfc41b3",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "95",
            "score1Date": "01/04",
            "practice2": true,
            "correct2": true,
            "score2": "100",
            "score2Date": "01/10",
            "practice3": true,
            "correct3": true,
            "score3": "80",
            "score3Date": "01/10"
          },
          {
            "id": 1767507146914.7537,
            "topic": "L8",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "95",
            "score1Date": "01/04",
            "practice2": true,
            "correct2": true,
            "score2": "80",
            "score2Date": "01/10",
            "practice3": true,
            "correct3": true,
            "score3": "76",
            "score3Date": "01/10"
          },
          {
            "id": 1767507150708.587,
            "topic": "L9",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "92",
            "score1Date": "01/04",
            "practice2": true,
            "correct2": true,
            "score2": "100",
            "score2Date": "01/10",
            "practice3": true,
            "correct3": true,
            "score3": "80",
            "score3Date": "01/10"
          },
          {
            "id": 1767461177303.824,
            "topic": "L10",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "98",
            "practice2": true,
            "correct2": true,
            "score2": "100",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "01/10",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.554,
            "topic": "自學(三)",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "85",
            "practice2": true,
            "correct2": true,
            "score2": "80",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/07",
            "score2Date": "01/10",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.129,
            "topic": "古文今讀 81~90則",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "98",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767608311505.0295,
            "topic": "總複習",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "2026-01-05",
            "practice1": true,
            "correct1": true,
            "score1": "99",
            "score1Date": "01/07",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_fvlcwyf9m",
        "name": "數學",
        "rows": [
          {
            "id": 1767461177303.4626,
            "topic": "4-1 因式分解法解一元二次方程式",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "87",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.3877,
            "topic": "4-2 配方法與一元二次方程式的公式解",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "61",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.5012,
            "topic": "4-3 一元二次方程式的應用",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "87",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.17,
            "topic": "5-1 相對與累積次數分配圖表",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "84",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/06",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767534902071.114,
            "topic": "Review(歷屆)",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "80",
            "score1Date": "01/04",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_8987vguie",
        "name": "自然",
        "rows": [
          {
            "id": 1767461177303.046,
            "topic": "5-1 溫度與溫度計",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "82",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.9592,
            "topic": "5-2 熱量與比熱",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "82",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.074,
            "topic": "5-3 熱對物質的影響",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "85",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/08",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767506639124.2988,
            "topic": "5-4 熱的傳播方式",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "85",
            "score1Date": "01/08",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          },
          {
            "id": 1767506643893.976,
            "topic": "6-1 元素的探索",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          },
          {
            "id": 1767506651688.9893,
            "topic": "6-2 元素週期表",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          },
          {
            "id": 1767506656125.726,
            "topic": "6-3 化合物與原子概念的發展",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          },
          {
            "id": 1767506661109.0437,
            "topic": "6-3 化合物與原子概念的發展",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          },
          {
            "id": 1767780833816.5176,
            "topic": "總複習",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "",
            "practice1": true,
            "correct1": true,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_pgzt27jf5",
        "name": "英語",
        "rows": [
          {
            "id": 1767461177303.1707,
            "topic": "L5",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "82",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/08",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": "",
            "dueDate": ""
          },
          {
            "id": 1767461177303.8013,
            "topic": "L6",
            "note": false,
            "practice1": false,
            "correct1": false,
            "score1": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "memo": "",
            "link": "",
            "dueDate": "",
            "score1Date": "",
            "score2Date": "",
            "score3Date": ""
          },
          {
            "id": 1767461177303.0364,
            "topic": "Review 3",
            "note": false,
            "practice1": false,
            "correct1": false,
            "score1": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "memo": "",
            "link": "",
            "dueDate": "",
            "score1Date": "",
            "score2Date": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_u7xsvw3k5",
        "name": "公民",
        "rows": [
          {
            "id": 1767461177303.3955,
            "topic": "L5 地方政府",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "89",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "dueDate": "2026-01-04",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": ""
          },
          {
            "id": 1767461177303.7646,
            "topic": "L6 政治參與",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "94",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "dueDate": "2026-01-04",
            "score1Date": "01/04",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": ""
          },
          {
            "id": 1767695258871.0486,
            "topic": "總複習",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "2026-01-04",
            "practice1": true,
            "correct1": true,
            "score1": "100",
            "score1Date": "01/06",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_3ulny2gej",
        "name": "歷史",
        "rows": [
          {
            "id": 1767461177303.786,
            "topic": "L5  西力衝擊下的東亞世界",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "84",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "memo": "",
            "link": "",
            "dueDate": "2026-01-04",
            "score1Date": "01/06",
            "score2Date": "01/06",
            "score3Date": "01/06"
          },
          {
            "id": 1767461177303.2815,
            "topic": "L6 清末變局與社會文化的變遷",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "93",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "dueDate": "2026-01-04",
            "score1Date": "01/06",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": ""
          },
          {
            "id": 1767611763562.582,
            "topic": "總複習",
            "note": false,
            "memo": "",
            "link": "",
            "dueDate": "2026-01-04",
            "practice1": false,
            "correct1": false,
            "score1": "",
            "score1Date": "",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "score2Date": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score3Date": ""
          }
        ]
      },
      {
        "id": "sub_1767461177303_kdt4n61bb",
        "name": "地理",
        "rows": [
          {
            "id": 1767461177303.406,
            "topic": " 第二篇 第1章東北亞的自然環境與文化",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "78",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "score1Date": "01/04",
            "dueDate": "2026-01-04",
            "score2Date": "01/06",
            "score3Date": "01/06",
            "memo": "",
            "link": ""
          },
          {
            "id": 1767461177303.4482,
            "topic": "第二篇 第2章 東北亞的經濟發展與挑戰",
            "note": false,
            "practice1": true,
            "correct1": true,
            "score1": "84",
            "practice2": false,
            "correct2": false,
            "score2": "",
            "practice3": false,
            "correct3": false,
            "score3": "",
            "dueDate": "2026-01-04",
            "score1Date": "01/07",
            "score2Date": "",
            "score3Date": "",
            "memo": "",
            "link": ""
          }
        ]
      }
    ]
  }
];